### ISSUE TITLE
Bug: Unable to add extension on linux

### ISSUE THREAD

**Issue by Jax-Tsai-zero** [block/goose#2351]
```bash
Error: Error activating extension: Failed to add extension configuration, error: Initialization(Stdio { name: "pdfreader", cmd: "/usr/lib/goose-desktop/resources/bin/uvx", args: ["mcp-read-pdf"], envs: Envs { map: {} }, timeout: Some(300), description: None, bundled: None }, McpServerError { method: "initialize", server: "", source: ServerBoxError(StdioProcessError("fatal:hermit: open /home/Jax-Tsai/.config/goose/mcp-hermit/bin/hermit: text file busy\n")) })
```

platform: arch linux

**Comment by dbirks** [comment]
Hey thanks for opening this issue. I was having troubles with this too, and just recently figured out a fix for it. Just pushed it to the AUR in this commit: https://aur.archlinux.org/cgit/aur.git/commit/?h=goose-desktop&id=bb616687159479ddaae952f80a5364ae720a7f4d

**Comment by ahau-square** [comment]
@Jax-Tsai-zero are you still seeing this issue? 

Thanks for the fix @dbirks !

**Comment by phlax** [comment]
im hitting this on a debian host - is there no way to avoid hermit - id never heard of it but afaict its not somethign i want at all

**Comment by phlax** [comment]
ah - i see - just replace the hermit scripts - wfm - thanks @dbirks

**Comment by gbtami** [comment]
dbirk suggestion worked for me as well on Ubuntu
I suggest to devs to add uv and npm packages as required dependencies of .deb/.rpm packages.

Hmm, uv is so new it has no .deb in debian/ubuntu at all.

**Comment by ryzen3100** [comment]
@dbirks 
Thanks it worked for Ubuntu distrobox container (Arch host).
```
sudo rm "/usr/lib/goose/resources/bin/npx"
sudo ln -s /usr/bin/npx "/usr/lib/goose/resources/bin/npx"
```

**Comment by samrocksc** [comment]
On ubuntu, running into the same issue, the symlink works though.  Seems like it's an electron issue.

**Comment by harkamals** [comment]
> [@dbirks](https://github.com/dbirks) Thanks it worked for Ubuntu distrobox container (Arch host).
> 
> ```
> sudo rm "/usr/lib/goose/resources/bin/npx"
> sudo ln -s /usr/bin/npx "/usr/lib/goose/resources/bin/npx"
> ```

thank you!

**Comment by airtonix** [comment]
I wouldn't be including any of these wrappers in that bin dir.

instead provide instructions for people to install these themselves.

I use Mise and so i have multiple different versions of node, python, go, whatever and i don't ever have a system version of a thing.

so goose fails to use npx or node unless i instruct it to run mcps with `mise x -- npx ... the thing`

**Comment by kristopolous** [comment]
so this description is still true. I see here: https://block.github.io/goose/extensions/ there's these "install" links that are url handler. Any of them will exhibit this. It doesn't matter.  I see in `/usr/share/applications` I have `goose.desktop` like so

```
[Desktop Entry]
Name=Goose
Comment=Goose App
GenericName=Goose
Exec=goose %U
Icon=goose
Type=Application
StartupNotify=true
Categories=Development;
MimeType=x-scheme-handler/goose;
```

so this means if I click on that "install" it will run:

```
"goose %U" 
```

Alright, all this does is open up a blank start page. It completely ignores all command line options as far as I can tell. 

I can see the "extension" is just arguments for the manual dialog box so I can fill them in manually, but this still doesn't work. For instance:

```bash
Error activating extension: Failed to add extension configuration, error: ProcessExit(ProcessExit { stderr: "2025-09-08 19:17:23 - Starting npx setup script.
2025-09-08 19:17:23 - Creating directory ~/.config/goose/mcp-hermit/bin if it does not exist.
2025-09-08 19:17:23 - Changing to directory ~/.config/goose/mcp-hermit.
2025-09-08 19:17:23 - Hermit binary already exists. Skipping download.
2025-09-08 19:17:23 - setting hermit cache to be local for MCP servers
2025-09-08 19:17:23 - Updated PATH to include ~/.config/goose/mcp-hermit/bin.
2025-09-08 19:17:23 - Checking for hermit in PATH.
2025-09-08 19:17:23 - Initializing hermit.
fatal:hermit: open /home/chris/.config/goose/mcp-hermit/bin/hermit: text file busy
2025-09-08 19:17:23 - An error occurred. Exiting with status 1.", source: ConnectionClosed("initialize response") })
```

V. 1.7.0

**Comment by wdawn** [comment]
i have the same problem with ubuntu.

**Comment by evdcush** [comment]
Same issue as @kristopolous (noop gui, error message cli):

> Alright, all this does is open up a blank start page. It completely ignores all command line options as far as I can tell.
> 
> I can see the "extension" is just arguments for the manual dialog box so I can fill them in manually, but this still doesn't work. For instance:
> 
> ```
> Error activating extension: Failed to add extension configuration, error: ProcessExit(ProcessExit { stderr: "2025-09-08 19:17:23 - Starting npx setup script.
> 2025-09-08 19:17:23 - Creating directory ~/.config/goose/mcp-hermit/bin if it does not exist.
> 2025-09-08 19:17:23 - Changing to directory ~/.config/goose/mcp-hermit.
> 2025-09-08 19:17:23 - Hermit binary already exists. Skipping download.
> 2025-09-08 19:17:23 - setting hermit cache to be local for MCP servers
> 2025-09-08 19:17:23 - Updated PATH to include ~/.config/goose/mcp-hermit/bin.
> 2025-09-08 19:17:23 - Checking for hermit in PATH.
> 2025-09-08 19:17:23 - Initializing hermit.
> fatal:hermit: open /home/chris/.config/goose/mcp-hermit/bin/hermit: text file busy
> 2025-09-08 19:17:23 - An error occurred. Exiting with status 1.", source: ConnectionClosed("initialize response") })
> ```
> V. 1.7.0


**v1.8.0, v1.9.0**


Here's what it looks like:


<details>
  <summary>Video 📼</summary>

https://github.com/user-attachments/assets/9c661223-1049-4ca9-9ecb-00e63670ef10

</details>

**Comment by kristopolous** [comment]
If it's any consolation, I have a mac mini m4 and it doesn't work on that thing either. I mean it at least registers but then a different error crops up

I know people who are using it successfully aren't really scrolling through this thread but if someone has had it previously working successfully, at all, that would be a nice data-point to have.

Maybe this feature just never worked.

**Comment by abda11ah** [comment]
same here on manjaro, i click install, it opens goose-desktop but no extension are added

**Comment by DOsinga** [comment]
seems like a dupe of #2351 /cc @zanesq

**Comment by zanesq** [comment]
Yes, it was a bug where extensions from deeplinks weren't actually installing on Mac and Windows and fixed now on main so it will be released soon in the next version > 1.9.1. I'll look into linux also next.

**Comment by IA386** [comment]
I can confirm that it still does not work with version 1.9.1/Debian Trixie.
The issue seems to be related to the Hermit environment’s self-update mechanism. When Goose tries to install an extension, it creates an `mcp-hermit` folder inside `~/.config/goose`. Then the `uvx` or `npx` scripts attempt to execute `hermit init`, which fails.

The problem is that the binary tries to update itself by copying a script over the existing binary file, which results in a **"text file busy"** error.

Here’s how I solved it:

```bash
user@host:$ cd ~/.config/goose/mcp-hermit/
user@host:~/.config/goose/mcp-hermit$ mv bin/hermit bin/hermit.real
user@host:~/.config/goose/mcp-hermit$ bin/hermit.real init
```

After that, I was able to install extensions in Goose manually using the **"Add custom extension"** button (deeplinks still do not work).

**Comment by zanesq** [comment]
Sorry greater than 1.9.1, can you confirm in 1.9.2? Here was the fix https://github.com/block/goose/pull/5041

**Comment by kristopolous** [comment]
```shell
Error activating extension: Failed to add extension configuration, error: ProcessExit(ProcessExit { stderr: "2025-10-15 12:38:31 - Starting node setup (common).
2025-10-15 12:38:31 - Creating directory ~/.config/goose/mcp-hermit/bin if it does not exist.
2025-10-15 12:38:31 - Changing to directory ~/.config/goose/mcp-hermit.
2025-10-15 12:38:31 - Hermit binary already exists. Skipping download.
2025-10-15 12:38:31 - setting hermit cache to be local for MCP servers
2025-10-15 12:38:31 - Updated PATH to include ~/.config/goose/mcp-hermit/bin.
2025-10-15 12:38:31 - Checking for hermit in PATH.
2025-10-15 12:38:31 - Initializing hermit.
fatal:hermit: open /home/chris/.config/goose/mcp-hermit/bin/hermit: text file busy
2025-10-15 12:38:31 - An error occurred. Exiting with status 1.
", source: ConnectionClosed("initialize response") })
```

Thats for context7

```shell
Package: goose
Version: 1.10.2
Status: install ok installed
Priority: optional
Section: utils
Maintainer: Block, Inc.
Installed-Size: 434 MB
Depends: libgtk-3-0, libnotify4, libnss3, xdg-utils, libatspi2.0-0, libdrm2, libgbm1, libxcb-dri3-0, kde-cli-tools | kde-runtime | trash-cli | libglib2.0-bin | gvfs-bin
Recommends: pulseaudio | libasound2
Suggests: gir1.2-gnomekeyring-1.0, libgnome-keyring0, lsb-release
Homepage: https://block.github.io/goose/
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: goose App
 goose App
```

**Comment by IA386** [comment]
Currently, the `npx`, `uvx`, and `jbang` scripts attempt to install Hermit by using the binary directly instead of the official Hermit installation script. Later, these scripts try to initialize the environment, and Hermit’s auto-update mechanism attempts to update itself. However, on Linux, the Hermit binary is locked by the system, which leads to the “text file busy” error.

This happens because the Hermit binary cannot be used as a standalone executable — it always tries to update itself. To fix this, either the installation logic in these scripts should be redesigned, or the issue should be raised with the upstream project.

This is how I solved the issue locally:
After the error appears, open a terminal and run the following commands:

```bash
mv ~/.config/goose/mcp-hermit/bin/hermit ~/.config/goose/mcp-hermit/bin/hermit.real

cat <<"EOF"> ~/.config/goose/mcp-hermit/bin/hermit && chmod 700 ~/.config/goose/mcp-hermit/bin/hermit
#!/usr/bin/env bash
shopt -s extglob
{
  # This script will be replaced by the Hermit update process
  HERMIT_EXE="$(dirname "${BASH_SOURCE[0]}")/hermit.real"
  $HERMIT_EXE "$@" && rm "$HERMIT_EXE"
  exit
}
EOF
```

Then, try installing the extension again.

**Comment by kristopolous** [comment]
This last suggestion does work for me in linux with a caveat. The brave search mcp has been removed from the goose extension boutique - I'm guessing it failed to pass a test because they renamed it.

The npx location has been changed: see https://github.com/brave/brave-search-mcp-server ... 

Change the command line to `npx -y @brave/brave-search-mcp-server` and you should be good to go

**Comment by admun** [comment]
I am running into this issue as well in Fedora 43, with Goose 1.12.1 installed from RPM.

I ended up replace all the bundled tools....

```ls -l /usr/lib/Goose/resources/bin
total 123944
-rwxr-xr-x. 1 root root 105654408 Oct 28 08:13 goosed
-rwxr-xr-x. 1 root root      3300 Oct 28 08:13 jbang
lrwxrwxrwx. 1 root root        13 Nov  2 17:40 node -> /usr/bin/node
-rwxr-xr-x. 1 root root      3499 Oct 28 08:13 node-setup-common.sh
lrwxrwxrwx. 1 root root        12 Nov  2 17:38 npx -> /usr/bin/npx
-rwxr-xr-x. 1 root root  21237864 Oct 28 08:13 temporal-service
lrwxrwxrwx. 1 root root        12 Nov  2 17:41 uvx -> /usr/bin/uvx
```

Maybe it just shouldn't bundle its own for Redhat based system?

**Comment by alexhancock** [comment]
I believe this to be fixed in https://github.com/block/goose/pull/5372

Upgrade to 1.13.1 of goose and re-open a specific issue if anything is still not working

**Comment by gbtami** [comment]
I tried 1.13.1 and faced with the same issue. First I thought this was still not fixed. But after reading through #5372 I find this comment:
"Note: After upgrading I had to delete the mcp hermit directory and then it worked: rm -rf ~/.config/goose/mcp-hermit"

After applying this, adding extensions works OK. This should be emphasized somewhere loudly IMO.

**Comment by alexhancock** [comment]
Thanks for the feedback @gbtami 

@The-Best-Codes Do you think there is a change we could make that would address the need for users to do this one time on linux? Maybe a small change to the script again?

**Comment by The-Best-Codes** [comment]
@alexhancock I made sure that Tania mentioned that in the release notes in the Discord server.
The problem is, if we add a script that automatically runs `rm -rf` on the directory, we'll also need to save some kind of marker file or flag to show that the patch (running `rm -rf`) has already been applied. Otherwise, it'll delete the directory again next time the script runs.
I mean it's not technically an issue but I feel like it adds more complexity. What do you think?

**Comment by alexhancock** [comment]
we could put some sentinel file on disk somewhere we can check the next time saying we've already done the initial removal

**Comment by The-Best-Codes** [comment]
@alexhancock Maybe something like this?

- Check if `~/.config/goose/mcp-hermit/.linux-fixed` (or similar) exists
- If not, rm -rf the dir, then `touch ~/.config/goose/mcp-hermit/.linux-fixed`
- If so then continue and don't rm the dir

**Comment by alexhancock** [comment]
yes
