### ISSUE TITLE
Recipe are still retained in the new chat when clicking "Home" on the menu bar

### ISSUE THREAD

**Issue by lifeizhou-ap** [block/goose#3774]
**Describe the bug**

Recipe is still retained in the new chat when clicking "Home" on the menu bar

**To Reproduce**
1. Using a recipe deeplink  or use a recipe from the recipe library
2. A chat appears with recipe 
3. Run the recipe
4. Click "Home" on the left hand side menu which starts a new chat
5. type "hello", it runs the recipe 

**Expected behavior**
In step 5, it should not run the recipe as it is a new session

**Please provide following information:**
 - **OS & Arch:** MacOS
 - **Interface:** [UI]
 - **Version:** 1.1.4

**Comment by zanesq** [comment]
This should be fixed now with the single agent refactor @lifeizhou-ap can you check?

**Comment by lifeizhou-ap** [comment]
Hi @zanesq, 

I tested again on `Version 1.7.0-block.202508291955-514c5 (1.7.0-block.202508291955-514c5)` desktop, it seems the issue is still there. 

https://github.com/user-attachments/assets/1bb10585-ae75-44ff-b96d-9fd2e5b5a09d

**Comment by zanesq** [comment]
@jamadeo has been looking into related functionality lately, any idea when we can support this / what it will take?

**Comment by jamadeo** [comment]
Should be fixed already in main as of https://github.com/block/goose/pull/4216/ @lifeizhou-ap

**Comment by lifeizhou-ap** [comment]
It is fixed
