### ISSUE TITLE
Installation issue for Ubuntu 22.04 due to libssl 3.1 incompatibility. musl build?

### ISSUE THREAD

**Issue by henryz2004** [block/goose#852]
The installation script on goose's website raises an error when run on Ubuntu 22.04 in a Docker container:

```
~# curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | sh
Downloading stable release: goose-x86_64-unknown-linux-gnu.tar.bz2...
Extracting goose-x86_64-unknown-linux-gnu.tar.bz2...
Moving goose to /root/.local/bin/goose

Configuring Goose

/root/.local/bin/goose: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

I tried manually installing openSSL 1.1 for Ubuntu in the Dockerfile like so:
```
RUN wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb && \
    dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb && \
    rm libssl1.1_1.1.0g-2ubuntu4_amd64.deb
```

But then I run into the error.
```
/root/.local/bin/goose: /lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /root/.local/bin/goose)
```

Does anyone know how to successfully install goose on ubuntu 22.04? I believe releasing a static/musl build will also work.

**Comment by rkuemon** [comment]
I have the same problem in Ubuntu (vmware) and WSL on Windows 11.

**Comment by henryz2004** [comment]
Works on Ubuntu 20.04 but not newer versions. Would be really nice to have this fixed because libssl 1.1 has reached end-of-life.

**Comment by baxen** [comment]
We're looking into updating our dependencies now!

**Comment by coldcanuk** [comment]
> We're looking into updating our dependencies now!

I can also confirm the same issue.

```
.......@Hermes:~/scripts$ ./gIssue.sh 
Goose Installation Issue Report
===============================
## Operating System
Distribution: Ubuntu 24.04.1 LTS
Version: 24.04
Codename: noble

## Kernel
Linux Hermes 6.8.0-51-generic #52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec  5 13:09:44 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

## SSL Library
libssl1.1: 0
Not installed
libssl3: 2

Detailed SSL package information:
ii  libssl3t64:amd64 3.0.13-0ubuntu3.4 amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl3t64:i386  3.0.13-0ubuntu3.4 i386         Secure Sockets Layer toolkit - shared libraries

## Goose
Goose version: goose: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Error: Unable to get version
Goose location: ~/.local/bin/goose

## Error Message
goose: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
Error: Unable to run goose

## PATH
~/.nvm/versions/node/v23.3.0/bin:~/.local/bin:~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:~/.dotnet/tools:~/.local/share/JetBrains/Toolbox/scripts:~/.local/bin:~/.local/bin

## Bash Version
5.2.21(1)-release

## Additional System Information
Architecture: x86_64
Processor: x86_64
......@Hermes:~/scripts$ 

```

**Comment by meenalc** [comment]
fyi, @wendytang and @michaelneale

**Comment by ahmedosman2001** [comment]
This is what worked for me 

`wget https://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb`

`sudo dpkg -i libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb`

`curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | sh`

**Comment by wendytang** [comment]
watching #868

**Comment by mp-fundament** [comment]
> This is what worked for me
> 
> `wget https://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb`
> 
> `sudo dpkg -i libssl1.1_1.1.1-1ubuntu2.1~18.04.23_amd64.deb`
> 
> `curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | sh`

https://stackoverflow.com/a/73604364
This post states that just installing libssl1.1 on Ubuntu 22 or 24 is risky. You'll revert a up-to-date package to an older version which is very likely less secure.

**Comment by dantetemplar** [comment]
same problem on Nobara Linux 40 (GNOME Edition)

**Comment by michaelneale** [comment]
@coldcanuk @rkuemon  @dantetemplar @mp-fundament @henryz2004  this should be fixed in canary release:

```sh
curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | CANARY=true bash
```

we don't actually need libssl, as we use `rust-tls`, but there was some misconfigured cargo.toml files which didnt explicitly exclude it - so hopefully that one solves it (yeah we don't want to use not up to date ssl).

**Comment by demirbey05** [comment]
Same for me, in Fedora 41

**Comment by mp-fundament** [comment]
> [@coldcanuk](https://github.com/coldcanuk) [@rkuemon](https://github.com/rkuemon) [@dantetemplar](https://github.com/dantetemplar) [@mp-fundament](https://github.com/mp-fundament) [@henryz2004](https://github.com/henryz2004) this should be fixed in canary release:
> 
> curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | CANARY=true bash
> we don't actually need libssl, as we use `rust-tls`, but there was some misconfigured cargo.toml files which didnt explicitly exclude it - so hopefully that one solves it (yeah we don't want to use not up to date ssl).

This worked, thanks.

**Comment by coldcanuk** [comment]
> [@coldcanuk](https://github.com/coldcanuk) [@rkuemon](https://github.com/rkuemon) [@dantetemplar](https://github.com/dantetemplar) [@mp-fundament](https://github.com/mp-fundament) [@henryz2004](https://github.com/henryz2004) this should be fixed in canary release:
> 
> curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | CANARY=true bash
> we don't actually need libssl, as we use `rust-tls`, but there was some misconfigured cargo.toml files which didnt explicitly exclude it - so hopefully that one solves it (yeah we don't want to use not up to date ssl).

Yeah I'm playing with codebase right now in cursor. Of course, the most complicated way first :) The simple way? BAH humbug to that :D lol

**Comment by salman1993** [comment]
we just released a stable version with this change, so this should work now for Ubuntu 22:
```
curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | bash
```

**Comment by jurjendevries** [comment]
Hi @salman1993  , I just downloaded Goose Desktop following the installation instructions by https://block.github.io/goose/docs/getting-started/installation/ and still have this issue

To reproduce:

1.     Download the desktop DEB file
2.     Navigate to the directory where it is saved in a terminal
3.     Run sudo dpkg -i goose_1.16.0_amd64.deb
4.     Launch goose from the app menu

<img width="1277" height="715" alt="Image" src="https://github.com/user-attachments/assets/12299217-254b-4bab-91cb-3a9c05faeff2" />

Your solution seems to be for the CLI.
Thanks for helping.
